<!DOCTYPE html>
<html lang="LV">

<head>
  <meta charset="UTF-8">
  <title>Sparkle Heart</title>
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="assets/font/font.css">
  <link rel="stylesheet" href="assets/style/mobile.css">
  <link rel="stylesheet" href="assets/style/image.css">
  <link rel="stylesheet" href="assets/style/media.css">
  <link rel="icon" type="image/x-icon" href="assets/img/Intersect.png">
</head>

<body>
  <header class="header">
    <div class="container">
      <div class="nav-wrapper">
        <a href="index.html"><img class="main-logo" src="assets/img/BlackLogo_3.jpg" alt="Company logo"></a>
        <button class="mobile-nav-toggle" aria-expanded="false">
          <img class="icon-hamburger" src="assets/img/hamburger.png" alt="Menu logo" aria-hidden="true">
          <span class="visually-hidden">Menu</span>
        </button>
        <div class="primary-navigation">
          <ul class="nav-list-lang">
            <li><a href="#latvian">LV</a></li>
            <li><a href="#english">EN</a></li>
            <li><a href="#russian">RU</a></li>
          </ul>
          <ul class="nav-list">
            <li><a href="#ideja">Ideja</a></li>
            <li><a href="#piesaki_sapni">Piesaki Sapni</a></li>
            <li><a href="#uznemejiem">Uzņēmējiem</a></li>
            <li><a href="#sapnu_banka">Sapņu banka</a></li>
            <li><a href="#sapnus_atbalsta">Sapņus atbalsta</a></li>
            <li><a href="#iedvesmas_stasti">99 Iedvesmas stāsti</a></li>
          </ul>
        </div>
      </div>
    </div>
  </header>
  <main>
    <div>
      <div class="video-photo">
        <img src="assets/img/Sparkle_Video_2.png" alt="video">
      </div>
    </div>
    <div class="text-about">
      <p>SparkleHeart ir biedrība, kas radīta, lai palīdzētu cilvēkiem piepildīt pat pārdrošākos
        sapņus. Šeit
        satiekas sapņotāji un viņu atbalstītāji - uzņēmumi, kas sniedz palīdzīgu roku, lai kopā pasauli
        padarītu par labāku vietu mums visiem.Mēs esam gatavi palīdzēt Tev piepildīt sapni. Kā pamats
        iedvesmai - tiek radīti arī 99 stāsti par Latvijas sievietēm.</p>
    </div>
    <div class="wrapper1">
      <div class="gallery">
        <div class="gallery__item gallery__item--1">
          <img src="assets/img/Zanda_1.jpg" class="gallery__image" alt="image1">
        </div>
        <div class="gallery__item gallery__item--2">
          <img src="assets/img/Sibilla_4.jpg" class="gallery__image" alt="image2">
        </div>
        <div class="gallery__item gallery__item--3">
          <img src="assets/img/Brinuma_meita_15.jpg" class="gallery__image" alt="image3">
        </div>
        <div class="gallery__item gallery__item--4">
          <img src="assets/img/Alina_1_1.jpg" class="gallery__image" alt="image4">
        </div>
        <div class="gallery__item gallery__item--5">
          <img src="assets/img/Anda_2_1.jpg" class="gallery__image" alt="image5">
        </div>
      </div>
    </div>
    <div class="even-columns-middle">
      <div>
        <h2 class="heading">VĒLIES PIEPILDĪT SAVU SAPNI?</h2>
        <div class="button-align">
          <button class="button">Sapņotājiem</button>
        </div>
      </div>
      <div>
        <h2 class="heading">VĒLIES PALĪDZĒT KĀDĀM PIEPILDĪT SAPNI?</h2>
        <div class="button-align">
          <button class="button lower-button">Uzņēmējiem</button>
        </div>
      </div>
    </div>
    <div class="wrapper">
      <div class="title">
        <h2>Sazināties ar mums</h2>
      </div>
      <div class="form">
        <div class="name-surname-email">
          <div class="input-field">
            <input type="text" class="input-name" value="Vārds, Uzvārds&#42;">
          </div>
          <div class="input-field">
            <input type="text" class="input-email" value="E-pasts&#42;">
          </div>
        </div>
        <div class="input-field">
          <input type="text" class="input-phone" value="Telefons&#42;">
        </div>
        <div class="input-field">
          <input type="text" class="input-question" value="Jautājums, vai komentārs&#42;">
        </div>
        <div class="input-field-terms">
          <input type="checkbox" class="box">
          <span class="agreement">Piekrītu, ka mani dati tiks izmantoti likumdošanā noteiktā kārtībā un tiks saglabāti
            līdz brīdim, kamēr tas būs nepieciešams.</span>
        </div>
        <div class="submit-button">
          <input type="submit" value="Sūtīt" class="btn">
        </div>
      </div>
    </div>
    <div class="above-footer">
      <div class="sponsor">
        <h3>atbalstītāji</h3>
      </div>
      <div class="sponsor-logo-flex">
        <div class="sponsor-logos">
          <div class="logo-1-div"><img class="logo-1" src="assets/img/getlogo_1.png" alt="sponsor logo 1"></div>
          <div class="logo-2-div"><img class="logo-2" src="assets/img/sem_logo_2_1.png" alt="sponsor logo 2"></div>
          <div class="logo-3-div"><img class="logo-3" src="assets/img/Citybee_logo_1.png" alt="sponsor logo 3"></div>
          <div class="logo-4-div"><img class="logo-4" src="assets/img/logo1_1.png" alt="sponsor logo 4"></div>
        </div>
      </div>
    </div>
  </main>
  <footer>
    <div class="footer">
      <div class="even-columns">
        <div class="left-section">
          <img class="yellow-logo" src="assets/img/GoldenV2Logo_3.png" alt="Yellow company logo">
          <p class="about-name-text-left">Juris Gogulis</p>
          <p class="copyright-paragraph-left">&#169; SparkleHeart 2020. Visas tiesības aizsargātas.</p>
        </div>
        <div class="left-middle-section">
          <nav>
            <ul class="nav-list-footer">
              <li><a href="#ideja">Ideja</a></li>
              <li><a href="#piesaki_sapni">Piesaki Sapni</a></li>
              <li><a href="#uznemejiem">Uzņēmējiem</a></li>
              <li><a href="#sapnu_banka">Sapņu banka</a></li>
              <li><a href="#sapnus_atbalsta">Sapņus atbalsta</a></li>
              <li><a href="#iedvesmas_stasti">99 Iedvesmas stāsti</a></li>
            </ul>
          </nav>
        </div>
        <div class="right-middle-section">
          <p class="prop-title">Biedrība SparkleHeart</p>
          <p class="prop">Reģistrācijas nr. 40008293119</p>
          <p class="prop">Banka: SWEDBANK A/S</p>
          <p class="prop">LV52HABA0551047652465</p>
        </div>
        <div class="right-section">
          <span class="about-name-text">Juris Gogulis</span>
          <p class="about-text about-text-title">juris.gogulis@sparkleheart.org</p>
          <p class="about-text">+37126890034</p>
          <p class="about-text">Biķernieku iela 24a - 5, LV-1006</p>
          <p class="text-link">Skatīt rekvizītus</p>
          <ul class="icons">
            <li><a aria-label="facebook" href="#"><img class="facebook-icon" src="assets/img/facebook.png"
                  alt="facebook logo"></a></li>
            <li><a aria-label="instagram" href="#"><img class="instagram-icon" src="assets/img/instagram.png"
                  alt="instagram logo"></a></li>
          </ul>
          <div>
            <p class="copyright-paragraph">&#169; SparkleHeart 2020. Visas tiesības aizsargātas.</p>
            <p class="politics-paragraph">Privātuma politika</p>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <script src="/assets/js/javascript.js"></script>
</body>

</html>
